# Generated by Django 4.1.1 on 2022-09-26 19:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("user", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(
                        height_field=100, upload_to="post_images", width_field=40
                    ),
                ),
                ("caption", models.TextField(max_length=300)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("no_likes", models.IntegerField()),
            ],
        ),
    ]
