# Generated by Django 4.1.1 on 2022-09-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_post_caption_alter_post_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="likepost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=100)),
                ("post_id", models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(upload_to="post_images"),
        ),
    ]
