# Generated by Django 4.1.1 on 2022-09-28 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_likepost_alter_post_image"),
    ]

    operations = [
        migrations.DeleteModel(name="likepost",),
    ]
